# Generated by Django 5.0.6 on 2026-05-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email_verification_token'),
        ('accounts', '0002_profile_avatar_url'),
    ]

    operations = [
    ]
