# Generated by Django 5.0.6 on 2025-11-12 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('price_level', models.IntegerField(default=2)),
                ('avg_rating', models.FloatField(default=0)),
                ('hours', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='coffee', max_length=50)),
                ('seasonal', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('flavor_tags', models.JSONField(blank=True, default=list)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='shops.coffeeshop')),
            ],
        ),
    ]
